### PR TITLE
Fix agents purge

### PR DESCRIPTION
**Pull request by Lifka**
Hello team,

this PR solves the issue https://github.com/wazuh/wazuh-api/issues/79, and it's part of https://github.com/wazuh/wazuh/tree/fix-agents-purge.

## Remove
* `POST/agents/purge`
* `GET/agents/purgeable`

## Add
* Filter `status` in `GET/agents` can filter by several status separated by commas. Sample: 
```
$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?status=Disconnected,neverconnected&pretty"
```
* Added new filter to `GET/agents` resquest: `timeframe`. Timeframe filters out agents that have not connected within the specified time. In case of having `never connected` status, filter using the date they were registered. Sample:
```
$ date
Tue May 22 09:49:01 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?pretty&timeframe=1s&status=neverconnected"
{
   "error": 0,
   "data": {
      "totalItems": 3,
      "items": [
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:27:49",
            "name": "agent001",
            "ip": "any",
            "id": "001",
            "node_name": "unknown"
         },
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:28:19",
            "name": "agent004",
            "ip": "any",
            "id": "004",
            "node_name": "unknown"
         },
         {
            "status": "Never connected",
            "dateAdd": "2018-05-22 09:36:31",
            "name": "agent_test1",
            "ip": "any",
            "id": "007",
            "node_name": "unknown"
         }
      ]
   }
}

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?pretty&timeframe=1h&status=neverconnected"
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:27:49",
            "name": "agent001",
            "ip": "any",
            "id": "001",
            "node_name": "unknown"
         },
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:28:19",
            "name": "agent004",
            "ip": "any",
            "id": "004",
            "node_name": "unknown"
         }
      ]
   }
}
```
```
$ date
Tue May 22 09:55:53 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?pretty&timeframe=2d&status=neverconnected,disconnected"
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "status": "Disconnected",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "group": "default",
            "name": "agent005",
            "mergedSum": "d9835ca466a5f6ede52e0684537f76bd",
            "ip": "any",
            "node_name": "node01",
            "dateAdd": "2018-05-20 09:55:29",
            "version": "Wazuh v3.2.3",
            "manager_host": "manager",
            "lastKeepAlive": "2018-05-20 09:55:29",
            "os": {
               "major": "7",
               "name": "CentOS Linux",
               "uname": "Linux |manager |3.10.0-693.17.1.el7.x86_64 |#1 SMP Thu Jan 25 20:13:58 UTC 2018 |x86_64",
               "platform": "centos",
               "version": "7",
               "codename": "Core",
               "arch": "x86_64"
            },
            "id": "005"
         }
      ]
   }
}
```
* Added `timeframe` and `status` filter to `DELETE /agents`. It's possible to delete agents not connected at a specific time with a specific status. By default, timeframe is `7d` (7 days). Samples:

Remove all agents that have been disconnected for the last week, or added more than a week ago and are never connected:

```
$ date
Tue May 22 10:09:57 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/003?pretty"
{
   "error": 0,
   "data": {
      "status": "Disconnected",
      "configSum": "ab73af41699f13fdd81903b5f23d8d00",
      "name": "agent003",
      "mergedSum": "d9835ca466a5f6ede52e0684537f76bd",
      "ip": "any",
      "dateAdd": "2018-05-15 10:09:09",
      "version": "Wazuh v3.2.3",
      "manager_host": "manager",
      "lastKeepAlive": "2018-05-15 10:09:09",
      "os": {
         "major": "7",
         "name": "CentOS Linux",
         "uname": "Linux |manager |3.10.0-693.17.1.el7.x86_64 |#1 SMP Thu Jan 24 10:13:58 UTC 2018 |x86_64",
         "platform": "centos",
         "version": "7",
         "codename": "Core",
         "arch": "x86_64"
      },
      "id": "003"
   }
}

$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&status=disconnected,neverconnected"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed",
      "affected_agents": [
         "003"
      ]
   }
}
```
Remove all agents from a list that have not been active from more than 1 day:
```
$ date
Tue May 22 10:14:41 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?pretty&timeframe=1d"       
{
   "error": 0,
   "data": {
      "totalItems": 3,
      "items": [
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:27:49",
            "name": "agent001",
            "ip": "any",
            "id": "001",
            "node_name": "unknown"
         },
         {
            "status": "Disconnected",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "name": "agent003",
            "mergedSum": "d9835ca466a5f6ede52e0684537f76bd",
            "ip": "any",
            "node_name": "node01",
            "dateAdd": "2018-05-21 09:28:08",
            "version": "Wazuh v3.2.3",
            "manager_host": "manager",
            "lastKeepAlive": "2018-05-15 10:09:09",
            "os": {
               "major": "7",
               "name": "CentOS Linux",
               "uname": "Linux |manager |3.10.0-693.17.1.el7.x86_64 |#1 SMP Thu Jan 24 10:13:58 UTC 2018 |x86_64",
               "platform": "centos",
               "version": "7",
               "codename": "Core",
               "arch": "x86_64"
            },
            "id": "003"
         },
         {
            "status": "Never connected",
            "dateAdd": "2018-05-21 09:28:19",
            "name": "agent004",
            "ip": "any",
            "id": "004",
            "node_name": "unknown"
         }
      ]
   }
}

$ curl -u foo:bar -k -X DELETE -H "Content-Type:application/json" -d '{"ids":["003","004","006"]}' "http://127.0.0.1:55000/agents?pretty&timeframe=1d"
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "failed_ids": [
         {
            "id": "006",
            "error": {
               "message": "Agent is not eligible for removal: The agent has a status different to 'all' or the specified timeframe '1d' does not apply.",
               "code": 1731
            }
         }
      ],
      "affected_agents": [
         "003",
         "004"
      ]
   }
}
```

Delete all agents never connected:
```
$ /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: agent002, IP: any, Disconnected
   ID: 005, Name: agent005, IP: any, Disconnected
   ID: 007, Name: agent_test1, IP: any, Never connected
   ID: 008, Name: agent_nc1, IP: any, Never connected
   ID: 009, Name: agent_nc2, IP: any, Never connected

List of agentless devices:

$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&status=neverconnected&timeframe=1s"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed",
      "affected_agents": [
         "007",
         "008",
         "009"
      ]
   }
}
$ /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: agent002, IP: any, Disconnected
   ID: 005, Name: agent005, IP: any, Disconnected

List of agentless devices:
```

Regards.

### CODE REVIEW

**Comment by mgmacias95** [comment]
Hello @Lifka,

Please, update the changelog and the mocha tests with these changes.

Best regards,
Marta

**Comment by Lifka** [comment]
Done.
Thanks for the review @mgmacias95!

**Comment by jesuslinares** [comment]
Great job!

Some changes:
 - timeframe -> older_than
 - older_than can't be used alone. It must be used with status (We don't want to remove Active agents easily)

Thanks.

**Comment by Lifka** [comment]
Done! 
`timeframe` is now `older_than`.
`older_than` can never be used alone:
```
$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty"
{
   "error": 604,
   "message": "Filter error. Missing field: You have to specified 'ids' or status."
}

$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&older_than=1s"
{
   "error": 604,
   "message": "Filter error. Missing field: You have to specified 'ids' or status."
}

```

Thank you @jesuslinares!

The last commit also fixes a bug handling python exceptions in agents functions:

Before:
```
$ curl -u foo:bar -k -X DELETE  "http://127.0.0.1:55000/agents?pretty&older_than=1s&status=neverconnected"
{
   "error": 1000,
   "message": "Wazuh-Python Internal Error: 'exceptions.Exception' object has no attribute 'code'"
}
```

Then:
```
$ curl -u foo:bar -k -X DELETE  "http://127.0.0.1:55000/agents?pretty&older_than=1s&status=neverconnected"
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "failed_ids": [
         {
            "id": "001",
            "error": {
               "message": "Sample exception",
               "code": 1000
            }
         },
         {
            "id": "002",
            "error": {
               "message": "Sample exception",
               "code": 1000
            }
         },
         {
            "id": "005",
            "error": {
               "message": "Sample exception",
               "code": 1000
            }
         }
      ],
      "older_than": "1s",
      "affected_agents": []
   }
}
```

**Comment by Lifka** [comment]
## Summary:

Requests for remove agents:
* `DELETE/agents`: Removes agents, using a list of them or a criterion based on the status or time of the last connection. 
    - `ids`: List of agents.
    - `status`: Filters by agent status. It's possible filter by several status using commas as a separator. Status can be `active`, `disconnected`, `pending` or `neverconnected`.
    - `older_than`: Filters out disconnected agents for longer than specified. Time in seconds or [n_days]d[n_hours]h[n_minutes]m[n_seconds]s. For never connected agents, uses the register date. By default is 7 days.
* `DELETE/agents/:agent_id`: Remove an agent.

Also, the filters `status` and `older_than` are availables in `GET/agents`.

## Samples:

Remove all agents that have been disconnected for the last week, or added more than a week ago and are never connected:

```
$ date
Thu May 24 16:01:53 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/004?pretty"
{
   "error": 0,
   "data": {
      "status": "Disconnected",
      "name": "agent004",
      "ip": "any",
      "dateAdd": "2018-05-17 16:01:44",
      "lastKeepAlive": "2018-05-17 16:01:44",
      "id": "004"
   }
}

$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&status=disconnected,neverconnected"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed",
      "older_than": "7d",
      "affected_agents": [
         "004"
      ]
   }
}
```

Remove all agents from a list that have not been active from more than 1 day:
```
$ date
Thu May 24 16:10:33 UTC 2018

$ curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents?pretty&status=Disconnected&older_than=1d&select=id,name,last_keepalive"
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "lastKeepAlive": "2018-05-23 16:08:11",
            "name": "ag-ubuntu",
            "id": "007"
         },
         {
            "lastKeepAlive": "2018-05-23 16:08:17",
            "name": "ag-redhat",
            "id": "008"
         }
      ]
   }
}

$ curl -u foo:bar -k -X DELETE -H "Content-Type:application/json" -d '{"ids":["004", "007"]}' "http://127.0.0.1:55000/agents?pretty&older_than=1d&status=disconnected"
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "failed_ids": [
         {
            "id": "004",
            "error": {
               "message": "Agent is not eligible for removal: The agent has a status different to 'disconnected' or the specified time frame 'older_than 1d' does not apply.",
               "code": 1731
            }
         }
      ],
      "older_than": "1d",
      "affected_agents": [
         "007"
      ]
   }
}
```

Remove all agents never connected:

```
$ /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent001, IP: any, Never connected
   ID: 002, Name: agent002, IP: any, Pending
   ID: 003, Name: agent003, IP: any, Never connected
   ID: 004, Name: agent004, IP: any, Pending
   ID: 005, Name: agent005, IP: any, Pending
   ID: 006, Name: agent106, IP: any, Active
   ID: 007, Name: ag-ubuntu, IP: any, Disconnected
   ID: 008, Name: ag-redhat, IP: any, Disconnected

List of agentless devices:

$ curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents?pretty&older_than=1s&status=neverconnected"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were removed",
      "older_than": "1s",
      "affected_agents": [
         "001",
         "003"
      ]
   }
}
$ /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: agent002, IP: any, Pending
   ID: 004, Name: agent004, IP: any, Pending
   ID: 005, Name: agent005, IP: any, Pending
   ID: 006, Name: agent106, IP: any, Active
   ID: 007, Name: ag-ubuntu, IP: any, Disconnected
   ID: 008, Name: ag-redhat, IP: any, Disconnected

List of agentless devices:

```

Regards!

**Pull request merged**
