### PR TITLE
Add call to purge disconnected agents

### PR DESCRIPTION
**Pull request by vikman90**
This new call will allow removing unused keys from the manager, purging agents that have not connected in a defined timeframe.

```sh
curl -u foo:bar -k -X POST -H "Content-Type:application/json" -d '{"timeframe":10800}' "http://127.0.0.1:55000/agents/purge?pretty"
```
```json
{
   "error": 0,
   "data": {
      "totalItems": 1
   }
}
```

### CODE REVIEW

**Comment by mgmacias95** [comment]
Hello @vikman90,

This PR looks amazing. I think the following suggestions would make it even better 😉 👍 
* [ ] Add a time unit for the timeframe. For example: 2m, 1d, 4h, 30s... 
* [ ] Add a `debug` parameter to return removed IDs or not.
* [ ] Add another API call: `GET/agents/purgeable` with `limit` and `offset` parameters.
* [ ] Add a `backup` parameter.

Also, don't forget to update the CHANGELOG.md file. 

Best regards,
Marta

**Comment by mgmacias95** [comment]
Amazing! Thank you so much @vikman90 and @Lifka 😄 !

**Comment by sonfrau** [comment]
Sorry for my ignorance but I'd like to use this new feature but I'm not able to find out  any example on your documentation. 

Would you mind to supply any related link?

Thanks and kind regards

**Comment by sonfrau** [comment]
I've got it: https://documentation.wazuh.com/current/user-manual/api/reference.html#agents

Thanks in any case

**Pull request merged**
