### PR TITLE
Calls for getting CDB lists

### PR DESCRIPTION
**Pull request by druizz90**
Hi team,

This PR is for adding new calls for getting CDB lists (issue #298). Below there are some examples of these new calls.

- `curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists`:

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=1&limit=3"
{
   "error": 0,
   "data": {
      "totalItems": 3,
      "items": [
         {
            "path": "etc/lists/amazon/aws-test",
            "items": [
               {
                  "key": "AttachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "DetachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "CreateSubnet",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateTags",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateVolume",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "DeletePlacementGroup",
                  "value": "Legacy Wazuh CDB"
               }
            ]
         },
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         },
         {
            "path": "etc/lists/aa-test-list",
            "items": [
               {
                  "key": "test-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "test-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "test-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "test-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "test-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}

```

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&search=audit"
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}
```

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&search=aws&offset=1"
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "path": "etc/lists/amazon/aws-test",
            "items": [
               {
                  "key": "AttachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "DetachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "CreateSubnet",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateTags",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateVolume",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "DeletePlacementGroup",
                  "value": "Legacy Wazuh CDB"
               }
            ]
         }
      ]
   }
}

```

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=2" 
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         },
         {
            "path": "etc/lists/aa-test-list",
            "items": [
               {
                  "key": "test-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "test-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "test-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "test-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "test-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}
```

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=2&limit=1"
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}
```

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=2&limit=2&sort=path" 
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "path": "etc/lists/aa-test-list",
            "items": [
               {
                  "key": "test-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "test-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "test-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "test-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "test-wazuh-c",
                  "value": "command"
               }
            ]
         },
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}
```

```bash
curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=2&limit=2&sort=-path"
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         },
         {
            "path": "etc/lists/aa-test-list",
            "items": [
               {
                  "key": "test-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "test-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "test-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "test-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "test-wazuh-c",
                  "value": "command"
               }
            ]
         }
      ]
   }
}
```

- `curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists/files`:

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists/files?pretty"
{
   "error": 0,
   "data": [
      {
         "path": "/var/ossec/etc/lists/amazon",
         "name": "aws-eventnames"
      },
      {
         "path": "/var/ossec/etc/lists/amazon",
         "name": "aws-test"
      },
      {
         "path": "/var/ossec/etc/lists",
         "name": "audit-keys"
      },
      {
         "path": "/var/ossec/etc/lists",
         "name": "aa-test-list"
      }
   ]
}

```

Best regards,

Demetrio.

### CODE REVIEW

**Comment by crd1985** [comment]
Hi!
In the last example, I would prefer not to show the full paths.
Thx!

**Comment by druizz90** [comment]
Hi,

I made changes for showing relative paths in the output:

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists?pretty&offset=1&limit=2&sort=-path"
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "path": "etc/lists/audit-keys",
            "items": [
               {
                  "key": "audit-wazuh-w",
                  "value": "write"
               },
               {
                  "key": "audit-wazuh-r",
                  "value": "read"
               },
               {
                  "key": "audit-wazuh-a",
                  "value": "attribute"
               },
               {
                  "key": "audit-wazuh-x",
                  "value": "execute"
               },
               {
                  "key": "audit-wazuh-c",
                  "value": "command"
               }
            ]
         },
         {
            "path": "etc/lists/amazon/aws-test",
            "items": [
               {
                  "key": "AttachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "DetachLoadBalancers",
                  "value": "Autoscaling"
               },
               {
                  "key": "CreateSubnet",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateTags",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "CreateVolume",
                  "value": "Legacy Wazuh CDB"
               },
               {
                  "key": "DeletePlacementGroup",
                  "value": "Legacy Wazuh CDB"
               }
            ]
         }
      ]
   }
}
```

```bash
curl -u foo:bar -k -X GET "http://127.0.0.1:55000/lists/files?pretty"                         
{
   "error": 0,
   "data": [
      {
         "path": "etc/lists/amazon",
         "name": "aws-eventnames"
      },
      {
         "path": "etc/lists/amazon",
         "name": "aws-test"
      },
      {
         "path": "etc/lists",
         "name": "audit-keys"
      },
      {
         "path": "etc/lists",
         "name": "aa-test-list"
      }
   ]
}
```

**Comment by druizz90** [comment]
Mocha tests were added @crd1985!

**Comment by crd1985** [comment]
Merging blocked by https://github.com/wazuh/wazuh/pull/2481

**Pull request merged**
