### PR TITLE
Avoid possible errors by removing the agent (if exists)

### PR DESCRIPTION
**Pull request by alexiacobws**

### CODE REVIEW

**Comment by BraulioV** [comment]
Hi @alexiacobws ,

first of all, thank you for your contribution. Reviewing your commit, I'm a bit concerned about the use of `jq`. As you said, it should be installed in order to use the script, and in any other case, the script will fail. To avoid these kinds of errors and to avoid adding `jq` as a Wazuh-API's dependency, can you change `jq` by `grep` and `cut`? It could be a bit tricky to add but the script can be used without installing any more dependencies.

Also, the script will always remove the agent, but it would be nice if the script asks you if you really want to delete that agent. Also, you can add an option `-f|--force` or `-q|--quiet` that will remove the agents without asking nothing. That would be awesome.

Thanks again.

Regards,
Braulio

**Comment by alexiacobws** [comment]
Sure, no problem. Thanks for the input.

**Comment by alexiacobws** [comment]
Hi @BraulioV 

I've updated the script to include the required flags when removing an existing agent.
The flags are: -f|--force and -s|--silent

Below are the test results:
Initial agent ID: 132
selection_001-2018-04-17-23 56 27

Display help:
```
root@inhouse-sonarqube:/tmp# ./api-register-agent.sh -h

    ./api-register-agent.sh  [-h] [-f|--force] [-q|--quiet] [agent]

   -h             Show this message.
   -f|--force     Force agent removal (if already registered)
                  The agent will be re-regitered with a new ID
   -s|--silent    Surpress the output while removing the agent
   agent          Agent name (if missing we will use the output
                  of the hostname command
```
Force flag:
```
root@inhouse-sonarqube:/tmp# ./api-register-agent.sh -f

Checking for Agent ID...
Found: 132
Removing previous registration for 'inhouse-sonarqube' using ID: 132 ...
{"error":0,"data":{"msg":"All selected agents were removed","affected_agents":["132"]}}

Adding agent:
curl -s -u ****:**** -k -X POST -d 'name=inhouse-sonarqube' http://*.*.*.*:*****/agents
Agent 'inhouse-sonarqube' with ID '"133"' added.
Key for agent '"133"' received.

Importing authentication key:

Agent information:
   ID:133
   Name:inhouse-sonarqube
   IP Address: *.*.*.*

Confirm adding it?(y/n): Added.

Restarting:

Killing ossec-logcollector .. 
Killing ossec-syscheckd .. 
Killing ossec-agentd .. 
Killing ossec-execd .. 
wazuh-modulesd not running ..
Wazuh v3.2.1 Stopped
Starting Wazuh v3.2.1 (maintained by Wazuh Inc.)...
Started wazuh-modulesd...
Started ossec-execd...
2018/04/17 22:58:54 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
Started ossec-agentd...
2018/04/17 22:58:54 ossec-syscheckd: ERROR: (1756): Duplicated directory given: '/etc'.
2018/04/17 22:58:54 ossec-syscheckd: ERROR: (1756): Duplicated directory given: '/bin'.
Started ossec-syscheckd...
Started ossec-logcollector...
Completed.
```
Force and silent flags (for removing an agent):
```
root@inhouse-sonarqube:/tmp# ./api-register-agent.sh -f -s

Checking for Agent ID...

Adding agent:
curl -s -u ****:**** -k -X POST -d 'name=inhouse-sonarqube' http://*.*.*.*:*****/agents
Agent 'inhouse-sonarqube' with ID '"134"' added.
Key for agent '"134"' received.

Importing authentication key:

Agent information:
   ID:134
   Name:inhouse-sonarqube
   IP Address: *.*.*.*

Confirm adding it?(y/n): Added.

Restarting:

Killing ossec-logcollector .. 
Killing ossec-syscheckd .. 
Killing ossec-agentd .. 
Killing ossec-execd .. 
wazuh-modulesd not running ..
Wazuh v3.2.1 Stopped
Starting Wazuh v3.2.1 (maintained by Wazuh Inc.)...
Started wazuh-modulesd...
Started ossec-execd...
2018/04/17 23:00:52 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
Started ossec-agentd...
2018/04/17 23:00:52 ossec-syscheckd: ERROR: (1756): Duplicated directory given: '/etc'.
2018/04/17 23:00:52 ossec-syscheckd: ERROR: (1756): Duplicated directory given: '/bin'.
Started ossec-syscheckd...
Started ossec-logcollector...
Completed.
```
After those 2 runs the agent is is now 134
selection_001-2018-04-18-00 01 47

**Comment by BraulioV** [comment]
Hi @alexiacobws ,

sorry for the late response. Awesome job! 

Thank you so much for your contribution :)

Regards,
Braulio

**Pull request merged**
