### PR TITLE
New call to edit files (rules, decoders, lists and ossec.conf)

### LINKED ISSUE #283: Edit files (decoders, rules, lists and ossec.conf) (local)
The following files must be editable from the API:
- etc/rules/*
- etc/decoders/*
- etc/lists/*
- etc/ossec.conf

```
GET /manager/files?path=<path>
PUT /manager/files?path=<path>
```

Requirements:
- Path must be relative: `etc/rules/my_rules.xml`.
- Allow only the following paths: `etc/rules/.+.xml`, `etc/decoders/.+.xml`,  `etc/lists/.+`, `etc/ossec.conf`.
- Deny a path containing "..": `text/../text`

### LINKED ISSUE #302: Error getting list content after updated it
Hi team,

If you edit the list content with a `POST` call to the `API` and immediately after you try to get the content with a `GET` call, you receive the response of the `POST` call.

image

Only it's happening in these calls.

Regards,

### PR DESCRIPTION
**Pull request by druizz90**
Hi team,

This PR is closes #283. I added two calls for getting and editing files (rules, decoders, lists and `ossec.conf`).

The last commit I added closes #302.

Below there are some examples:

```bash
# cat rules.xml 
<!-- Local rules -->

<!-- Modify it at your will. -->

<!-- Example -->
<group name="local,">

  <!--
   NEW RULE 
   -->
   <rule id="100001111" level="5">
     <if_sid>5716</if_sid>
     <srcip>1.1.1.1</srcip>
     <description>sshd: authentication failed from IP 1.1.1.1.</description>
     <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
   </rule>
</group>

# curl -u foo:bar -X POST -H "Content-type:application/xml" -d @/home/druizz/rules.xml "http://localhost:55000/manager/files?path=etc/rules/new_rules.xml"
{"error":0,"data":"File updated successfully"}

# curl -u foo:bar -X GET "http://localhost:55000/manager/files?path=etc/rules/new_rules.xml"   
{"error":0,"data":"  <!-- Local rules -->\n  <!-- Modify it at your will. -->\n  <!-- Example -->\n  <group name=\"local,\">\n    <!--   NEW RULE    -->\n    <rule id=\"100001111\" level=\"5\">\n      <if_sid>5716</if_sid>\n      <srcip>1.1.1.1</srcip>\n      <description>sshd: authentication failed from IP 1.1.1.1.</description>\n      <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>\n    </rule>\n  </group>\n"}

# cat /var/ossec/etc/rules/new_rules.xml 
  <!-- Local rules -->
  <!-- Modify it at your will. -->
  <!-- Example -->
  <group name="local,">
    <!--   NEW RULE    -->
    <rule id="100001111" level="5">
      <if_sid>5716</if_sid>
      <srcip>1.1.1.1</srcip>
      <description>sshd: authentication failed from IP 1.1.1.1.</description>
      <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
    </rule>
  </group>
```

```bash
# cat decoders.xml  
<!-- NEW Local Decoders -->

<!-- Modify it at your will. -->

<decoder name="local_decoder_example">
    <program_name>NEW DECODER</program_name>
</decoder>

# curl -u foo:bar -X POST -H 'Content-type: application/xml' -d @/home/druizz/decoders.xml "http://localhost:55000/manager/files?path=etc/decoders/new_decoders.xml"   
{"error":0,"data":"File updated successfully"}

# curl -u foo:bar -X GET "http://localhost:55000/manager/files?path=etc/decoders/new_decoders.xml"                                                           
{"error":0,"data":"  <!-- NEW Local Decoders -->\n  <!-- Modify it at your will. -->\n  <decoder name=\"local_decoder_example\">\n    <program_name>NEW DECODER</program_name>\n  </decoder>\n"}

# cat /var/ossec/etc/decoders/new_decoders.xml 
  <!-- NEW Local Decoders -->
  <!-- Modify it at your will. -->
  <decoder name="local_decoder_example">
    <program_name>NEW DECODER</program_name>
  </decoder>
```

```bash
# cat list.txt                                                                                                                                                          
audit-wazuh-w:write
audit-wazuh-r:read
audit-wazuh-a:attribute
audit-wazuh-x:execute
audit-wazuh-c:command

# curl -u foo:bar -X POST -H "Content-type:application/octet-stream" --data-binary @/home/druizz/list.txt "http://localhost:55000/manager/files?path=etc/lists/new_list"
{"error":0,"data":"File updated successfully"}

# curl -u foo:bar -X GET "http://localhost:55000/manager/files?path=etc/lists/new_list"                                                                      
{"error":0,"data":"audit-wazuh-w:write\naudit-wazuh-r:read\naudit-wazuh-a:attribute\naudit-wazuh-x:execute\naudit-wazuh-c:command\n"}

# cat /var/ossec/etc/lists/new_list
audit-wazuh-w:write
audit-wazuh-r:read
audit-wazuh-a:attribute
audit-wazuh-x:execute
audit-wazuh-c:command
```

Best regards,

Demetrio.

### CODE REVIEW

**Comment by crd1985** [comment]
Hi,
could you provide some tests trying relative paths and non-utf8 encoded files?
I would like to guarantee the API does not crash in these specific cases and avoid some security risks.
Thanks!

**Comment by druizz90** [comment]
Hi,

This is an example using a file with `latin1` encoding with non common symbols:

```bash
# cat test_no_utf8 
<!-- NEW Local Decoders -->

<!-- Modify it at your will. -->

<decoder name="local_decoder_example">
    <program_name>ÃdasdfdfweÃ³Ã±NEW DECODER</program_name>
</decoder>

# curl -u foo:bar -X POST -H 'Content-type: application/xml' -d @/home/druizz/test_no_utf8 "http://localhost:55000/manager/files?path=etc/decoders/new_decoders.xml"
{"error":0,"data":"File updated successfully"}

# curl -u foo:bar -X GET "http://localhost:55000/manager/files?path=etc/decoders/new_decoders.xml"
{"error":0,"data":"  <!-- NEW Local Decoders -->\n  <!-- Modify it at your will. -->\n  <decoder name=\"local_decoder_example\">\n    <program_name>ÃdasdfdfweÃ³Ã±NEW DECODER</program_name>\n  </decoder>\n"}

# cat /var/ossec/etc/decoders/new_decoders.xml
  <!-- NEW Local Decoders -->
  <!-- Modify it at your will. -->
  <decoder name="local_decoder_example">
    <program_name>ÃdasdfdfweÃ³Ã±NEW DECODER</program_name>
  </decoder>
```

**Comment by druizz90** [comment]
The last commit I added closes issue #302.

**Comment by druizz90** [comment]
#### Unit tests

```bash
python3 -m pytest -v
================================================ test session starts =================================================
platform linux -- Python 3.6.3, pytest-4.2.0, py-1.7.0, pluggy-0.8.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: wazuh/framework, inifile:
collected 2 items

tests/test_manager.py::TestManager::test_get_file PASSED                                                       [ 50%]
tests/test_manager.py::TestManager::test_upload_file PASSED                                                    [100%]
```

#### Mocha tests

```bash
$ mocha test/test_manager.js

  Manager

POST/manager/files
      ✓ Upload rules (239ms)
      ✓ Upload decoder (234ms)
      ✓ Upload list (259ms)
      ✓ Upload malformed list
      ✓ Upload malformed rule
      ✓ Upload malformed decoder
      ✓ Upload malformed list
    /manager/files
      ✓ Request rules (228ms)
      ✓ Request decoders (249ms)
      ✓ Request lists (231ms)
      ✓ Request wrong path 1
      ✓ Request wrong path 2
      ✓ Request wrong path 3
      ✓ Request unexisting file (257ms)
```

**Pull request merged**
